version: '3.8'

services:
  couchbase:
    image: couchbase/server:7.2.0
    container_name: notification_couchbase
    ports:
      - "8091:8091"   # YÃ¶netim Paneli
      - "8093:8093"   # Query Service (N1QL)
      - "11210:11210" # Data Service 
    environment:
      - COUCHBASE_ADMINISTRATOR_USERNAME=admin
      - COUCHBASE_ADMINISTRATOR_PASSWORD=password123
    volumes:
      - ./couchbase-data:/opt/couchbase/var